COUNTRIES = [
  [ "Nigeria", "NG" ],
  [ "Benin", "BJ" ],
  [ "Burkina Faso", "BF" ],
  [ "Cameroon", "CM" ],
  [ "Chad", "TD" ],
  [ "Congo (Brazzaville)", "CG" ],
  [ "Congo (DRC)", "CD" ],
  [ "Côte d'Ivoire", "CI" ],
  [ "France", "FR" ],
  [ "Gabon", "GA" ],
  [ "Ghana", "GH" ],
  [ "Guinea", "GN" ],
  [ "Kenya", "KE" ],
  [ "Liberia", "LR" ],
  [ "Mali", "ML" ],
  [ "Mozambique", "MZ" ],
  [ "Senegal", "SN" ],
  [ "Sierra Leone", "SL" ],
  [ "Tanzania", "TZ" ],
  [ "United Arab Emirates", "AE" ],
  [ "United Kingdom", "GB" ],
  [ "United States", "US" ],
  [ "Uganda", "UG" ],
  [ "Zambia", "ZM" ]
].freeze
