default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# sqlite: &sqlite
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

development:
  primary: &primary_development
    <<: *default
    database: compliance_development
    username: UB
    password: postgres42
    host: localhost

  queue:
    <<: *primary_development
    database: compliance_development_queue
    migrations_paths: db/queue_migrate

  cache:
    <<: *primary_development
    database: compliance_development_cache
    migrations_paths: db/cache_migrate

  cable:
    <<: *primary_development
    database: compliance_development_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB") %>
    username: <%= ENV.fetch("POSTGRES_USER") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
    host: <%= ENV.fetch("POSTGRES_HOST") %>
    port: <%= ENV.fetch("POSTGRES_PORT") %>

  queue:
    <<: *primary_production
    database: <%= ENV.fetch("QUEUE_DB") %>
    migrations_paths: db/queue_migrate

  cache:
    <<: *primary_production
    database: <%= ENV.fetch("CACHE_DB") %>
    migrations_paths: db/cache_migrate

  cable:
    <<: *primary_production
    database: <%= ENV.fetch("CABLE_DB") %>
    migrations_paths: db/cable_migrate
