default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# sqlite: &sqlite
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

development:
  primary:
    <<: *default
    database: uba_compliance_development
    username: UB
    password: postgres42
    host: localhost

test:
  primary:
    <<: *default
    database: uba_compliance_test
    username: UB
    password: postgres42
    host: localhost

production:
  primary:
    <<: *default
    database: compliance_production
    username: deploy
    password: choose_a_strong_password
    host: 172.17.0.1
    port: 5432
