default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# sqlite: &sqlite
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

development:
  primary:
    <<: *default
    database: uba_compliance_development
    username: UB
    password: postgres42
    host: localhost

test:
  primary:
    <<: *default
    database: uba_compliance_test
    username: UB
    password: postgres42
    host: localhost

production:
  primary:
    <<: *default
    database: <%= ENV["DB_NAME"] %>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV["DB_PORT"] %>
